apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::633897975342:role/UdacityFlaskDeployCBKubectlRole
      username: build     
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::633897975342:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6KKN2C93OZSI
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-23T17:28:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-23T17:28:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1554"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0aafd865-ec90-4c5a-a39b-2c2ddd8aaeee
